// @workspace/api-client-react — React-Query client (generated by Orval)
// This package is currently unused in this repo. The stub exists to satisfy
// the pnpm workspace glob `shared/*` and Dockerfile COPY commands.
export {}
